name: Validate Markers

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - 'src/markers/**.tsv'
      - '.github/workflows/**.yaml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "ontology_qc"
  validate-inputs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: validate markers
        run: python ./src/scripts/marker_validator.py
      - id: marker-report
        name: generate report
        if: ${{ failure() }}
        run: |
          output=$(python ./src/scripts/marker_validator.py --silent)
          echo "::set-output name=validation-report::$output"
      - name: mail failure report
        if: ${{ failure() }}
        run: |
            echo validation-report ${{ steps.marker-report.outputs.validation-report }}
        shell: bash